/**
 * 测试题目初始化脚本
 * 用法: ts-node scripts/seed-quiz-questions.ts
 */

// 👇 添加这两行来加载 .env.local 文件
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { db } from "../src/db";
import { quizQuestions } from "../src/db/schema";

// 中文版题目数据（25题）
const zhQuestions = [
  {
    question_number: 1,
    category: "TF",
    locale: "zh",
    question_text: "我偏好比自己更成熟的人",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 2,
    category: "EI",
    locale: "zh",
    question_text: "我很容易被人吸引并坠入爱河",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 3,
    category: "EI",
    locale: "zh",
    question_text: "有伴侣的时候，我会尽量避免出现在异性聚集的地方",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "I",
    option_b_value: "E",
    weight: 1,
  },
  {
    question_number: 4,
    category: "TF",
    locale: "zh",
    question_text: "相对来说，我比较倾向迎合恋人",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 5,
    category: "JP",
    locale: "zh",
    question_text: "有单恋的倾向",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 6,
    category: "JP",
    locale: "zh",
    question_text: "和恋人在一起时，你通常哪种感受更强烈？",
    option_a_label: "去我自己想去的地方",
    option_b_label: "去伴侣想去的地方",
    option_a_value: "J",
    option_b_value: "P",
    weight: 1,
  },
  {
    question_number: 7,
    category: "SN",
    locale: "zh",
    question_text: "如果要选的话，你更倾向于：",
    option_a_label: "会逐渐喜欢上一个人",
    option_b_label: "会突然喜欢上一个人",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 8,
    category: "JP",
    locale: "zh",
    question_text: "在恋爱中，我常常比较被动，容易被对方牵着走",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 9,
    category: "EI",
    locale: "zh",
    question_text: "你的伴侣是否曾说过你很黏人，或者你自己有没有觉得自己很黏人？",
    option_a_label: "有",
    option_b_label: "没有",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 10,
    category: "TF",
    locale: "zh",
    question_text: "我有时会觉得伴侣孩子气又可爱",
    option_a_label: "有",
    option_b_label: "没有",
    option_a_value: "T",
    option_b_value: "F",
    weight: 1,
  },
  {
    question_number: 11,
    category: "JP",
    locale: "zh",
    question_text: "你觉得在爱情中，自己哪一面更强烈？",
    option_a_label: "自由随性",
    option_b_label: "认真严肃",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 12,
    category: "TF",
    locale: "zh",
    question_text: "如果你的伴侣在约会回家的路上，提议绕道散步，你会怎么做？",
    option_a_label: "如果我很累，可能会拒绝",
    option_b_label: "就算有点累，我也会答应",
    option_a_value: "T",
    option_b_value: "F",
    weight: 1,
  },
  {
    question_number: 13,
    category: "SN",
    locale: "zh",
    question_text: "你在寻找伴侣时，通常是什么心态？",
    option_a_label: "我对理想型有明确的印象，而且这个想法几乎不会改变",
    option_b_label: "我的理想型是自己爱上的人",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 14,
    category: "EI",
    locale: "zh",
    question_text: "你觉得自己在恋爱中属于喜欢掌握主导权的人吗？",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 15,
    category: "JP",
    locale: "zh",
    question_text: "对于朋友以上、恋人未满的关系",
    option_a_label: "我能享受它保持现状",
    option_b_label: "我希望能尽快开始交往",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 16,
    category: "SN",
    locale: "zh",
    question_text: "你能清楚、逻辑地解释自己为什么会喜欢上一个人吗？",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 17,
    category: "TF",
    locale: "zh",
    question_text: "如果伴侣想要你陪他去逛一间你没兴趣的店，你会怎么做？",
    option_a_label: "为了让对方开心，我会去",
    option_b_label: "老实说，我不太想去",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 18,
    category: "JP",
    locale: "zh",
    question_text: "交往之后，你希望伴侣对你有多少关心或干涉？",
    option_a_label: "希望少一点干涉，能保有自由",
    option_b_label: "如果对方在意我、关心我，我会觉得很开心",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 19,
    category: "TF",
    locale: "zh",
    question_text: "你偶尔会幻想什么样的爱人？",
    option_a_label: "能温柔接纳我的人",
    option_b_label: "让我想要去守护的人",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 20,
    category: "SN",
    locale: "zh",
    question_text: "你认为自己是哪种类型？",
    option_a_label: "会认真考虑未来的人",
    option_b_label: "只要当下喜欢对方就足够的人",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 21,
    category: "JP",
    locale: "zh",
    question_text: "交往之后，你的生活会有什么变化？",
    option_a_label: "和朋友相处或投入兴趣的时间，和交往前差不多",
    option_b_label: "恋人会成为我最优先考虑的人",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 22,
    category: "EI",
    locale: "zh",
    question_text: "当有人宠爱你时，你会因为「被需要」而感到幸福吗？",
    option_a_label: "是",
    option_b_label: "否",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 23,
    category: "SN",
    locale: "zh",
    question_text: "你认为自己更接近哪一种类型？",
    option_a_label: "比起理想或条件，更重视内心的喜欢感觉",
    option_b_label: "会明确思考并认真寻找符合理想的人",
    option_a_value: "N",
    option_b_value: "S",
    weight: 1,
  },
  {
    question_number: 24,
    category: "JP",
    locale: "zh",
    question_text: "你的恋爱风格是什么？",
    option_a_label: "诚恳专注，会认真对待对方",
    option_b_label: "自由随性，按照自己步调去爱",
    option_a_value: "J",
    option_b_value: "P",
    weight: 1,
  },
  {
    question_number: 25,
    category: "TF",
    locale: "zh",
    question_text: "约会前对方说「还是想去别的地方」的话？",
    option_a_label: "如果对方能开心就觉得无所谓",
    option_b_label: "先谈谈再说",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
];

// 日语版题目数据（25题）
const jaQuestions = [
  {
    question_number: 1,
    category: "TF",
    locale: "ja",
    question_text: "私は自分より成熟した人を好む",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 2,
    category: "EI",
    locale: "ja",
    question_text: "私は人に惹かれて恋に落ちやすい",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 3,
    category: "EI",
    locale: "ja",
    question_text: "パートナーがいる時、異性が多い場所にはなるべく行かない",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "I",
    option_b_value: "E",
    weight: 1,
  },
  {
    question_number: 4,
    category: "TF",
    locale: "ja",
    question_text: "どちらかというと、恋人に合わせる傾向がある",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 5,
    category: "JP",
    locale: "ja",
    question_text: "片思いをしやすい傾向がある",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 6,
    category: "JP",
    locale: "ja",
    question_text: "恋人と一緒にいる時、どちらの気持ちが強いですか？",
    option_a_label: "自分が行きたい場所に行く",
    option_b_label: "パートナーが行きたい場所に行く",
    option_a_value: "J",
    option_b_value: "P",
    weight: 1,
  },
  {
    question_number: 7,
    category: "SN",
    locale: "ja",
    question_text: "選ぶとしたら、どちらに傾向しますか？",
    option_a_label: "徐々に人を好きになる",
    option_b_label: "突然人を好きになる",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 8,
    category: "JP",
    locale: "ja",
    question_text: "恋愛では受け身で、相手に引っ張られやすい",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 9,
    category: "EI",
    locale: "ja",
    question_text: "パートナーから「甘えん坊」と言われたことがあるか、自分でそう思いますか？",
    option_a_label: "ある",
    option_b_label: "ない",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 10,
    category: "TF",
    locale: "ja",
    question_text: "パートナーが子供っぽくて可愛いと思うことがある",
    option_a_label: "ある",
    option_b_label: "ない",
    option_a_value: "T",
    option_b_value: "F",
    weight: 1,
  },
  {
    question_number: 11,
    category: "JP",
    locale: "ja",
    question_text: "恋愛において、自分のどちらの面が強いと思いますか？",
    option_a_label: "自由で気ままな面",
    option_b_label: "真面目で真剣な面",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 12,
    category: "TF",
    locale: "ja",
    question_text: "デートの帰り道、パートナーが散歩を提案したらどうしますか？",
    option_a_label: "疲れていたら断るかも",
    option_b_label: "少し疲れていても付き合う",
    option_a_value: "T",
    option_b_value: "F",
    weight: 1,
  },
  {
    question_number: 13,
    category: "SN",
    locale: "ja",
    question_text: "パートナーを探す時、どんな心境ですか？",
    option_a_label: "理想のタイプが明確で、ほとんど変わらない",
    option_b_label: "好きになった人が理想のタイプ",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 14,
    category: "EI",
    locale: "ja",
    question_text: "恋愛で主導権を握るタイプだと思いますか？",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 15,
    category: "JP",
    locale: "ja",
    question_text: "友達以上、恋人未満の関係について",
    option_a_label: "そのままの状態を楽しめる",
    option_b_label: "早く交際を始めたい",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 16,
    category: "SN",
    locale: "ja",
    question_text: "なぜその人を好きになったか、明確に論理的に説明できますか？",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 17,
    category: "TF",
    locale: "ja",
    question_text: "パートナーが興味のない店に付き合ってほしいと言ったら？",
    option_a_label: "相手を喜ばせるために行く",
    option_b_label: "正直あまり行きたくない",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 18,
    category: "JP",
    locale: "ja",
    question_text: "交際後、パートナーにどれくらい関心や干渉を望みますか？",
    option_a_label: "干渉は少なめで自由がほしい",
    option_b_label: "気にかけてくれると嬉しい",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 19,
    category: "TF",
    locale: "ja",
    question_text: "時々、どんな恋人を想像しますか？",
    option_a_label: "優しく受け入れてくれる人",
    option_b_label: "守りたいと思える人",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 20,
    category: "SN",
    locale: "ja",
    question_text: "自分はどちらのタイプだと思いますか？",
    option_a_label: "将来を真剣に考える人",
    option_b_label: "今好きならそれで十分な人",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 21,
    category: "JP",
    locale: "ja",
    question_text: "交際後、生活にどんな変化がありますか？",
    option_a_label: "友達や趣味の時間は交際前とほぼ同じ",
    option_b_label: "恋人が最優先になる",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 22,
    category: "EI",
    locale: "ja",
    question_text: "誰かに愛されている時、「必要とされている」ことで幸せを感じますか？",
    option_a_label: "はい",
    option_b_label: "いいえ",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 23,
    category: "SN",
    locale: "ja",
    question_text: "自分はどちらのタイプに近いと思いますか？",
    option_a_label: "理想や条件より、好きという気持ちを重視",
    option_b_label: "理想に合う人を明確に探す",
    option_a_value: "N",
    option_b_value: "S",
    weight: 1,
  },
  {
    question_number: 24,
    category: "JP",
    locale: "ja",
    question_text: "あなたの恋愛スタイルは？",
    option_a_label: "誠実で真剣に相手と向き合う",
    option_b_label: "自由気ままに自分のペースで愛する",
    option_a_value: "J",
    option_b_value: "P",
    weight: 1,
  },
  {
    question_number: 25,
    category: "TF",
    locale: "ja",
    question_text: "デート前に相手が「やっぱり別の場所に行きたい」と言ったら？",
    option_a_label: "相手が喜ぶなら構わない",
    option_b_label: "まず話し合う",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
];

// 英语版题目数据（25题）
const enQuestions = [
  {
    question_number: 1,
    category: "TF",
    locale: "en",
    question_text: "I prefer people who are more mature than me",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 2,
    category: "EI",
    locale: "en",
    question_text: "I easily get attracted to people and fall in love",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 3,
    category: "EI",
    locale: "en",
    question_text: "When I have a partner, I try to avoid places where many people of the opposite sex gather",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "I",
    option_b_value: "E",
    weight: 1,
  },
  {
    question_number: 4,
    category: "TF",
    locale: "en",
    question_text: "Relatively speaking, I tend to accommodate my partner",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 5,
    category: "JP",
    locale: "en",
    question_text: "I have a tendency to have unrequited love",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 6,
    category: "JP",
    locale: "en",
    question_text: "When you're with your partner, which feeling is usually stronger?",
    option_a_label: "Going where I want to go",
    option_b_label: "Going where my partner wants to go",
    option_a_value: "J",
    option_b_value: "P",
    weight: 1,
  },
  {
    question_number: 7,
    category: "SN",
    locale: "en",
    question_text: "If you had to choose, which do you tend toward?",
    option_a_label: "Gradually falling for someone",
    option_b_label: "Suddenly falling for someone",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 8,
    category: "JP",
    locale: "en",
    question_text: "In relationships, I'm often passive and easily led by my partner",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 9,
    category: "EI",
    locale: "en",
    question_text: "Has your partner ever said you're clingy, or do you feel you're clingy?",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 10,
    category: "TF",
    locale: "en",
    question_text: "I sometimes think my partner is childish and cute",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "T",
    option_b_value: "F",
    weight: 1,
  },
  {
    question_number: 11,
    category: "JP",
    locale: "en",
    question_text: "In love, which side of you is stronger?",
    option_a_label: "Free-spirited",
    option_b_label: "Serious and committed",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 12,
    category: "TF",
    locale: "en",
    question_text: "If your partner suggests taking a walk on the way home from a date, what would you do?",
    option_a_label: "I might decline if I'm tired",
    option_b_label: "I'd go even if I'm a bit tired",
    option_a_value: "T",
    option_b_value: "F",
    weight: 1,
  },
  {
    question_number: 13,
    category: "SN",
    locale: "en",
    question_text: "When looking for a partner, what's your usual mindset?",
    option_a_label: "I have a clear image of my ideal type and it rarely changes",
    option_b_label: "My ideal type is whoever I fall in love with",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 14,
    category: "EI",
    locale: "en",
    question_text: "Do you think you're the type who likes to take the lead in relationships?",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 15,
    category: "JP",
    locale: "en",
    question_text: "Regarding a relationship that's more than friends but less than lovers",
    option_a_label: "I can enjoy keeping it as is",
    option_b_label: "I hope to start dating soon",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 16,
    category: "SN",
    locale: "en",
    question_text: "Can you clearly and logically explain why you fell for someone?",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 17,
    category: "TF",
    locale: "en",
    question_text: "If your partner wants you to accompany them to a store you're not interested in, what would you do?",
    option_a_label: "I'd go to make them happy",
    option_b_label: "Honestly, I don't really want to go",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 18,
    category: "JP",
    locale: "en",
    question_text: "After starting a relationship, how much attention or involvement do you want from your partner?",
    option_a_label: "I prefer less interference and more freedom",
    option_b_label: "I'd be happy if they care about me and show concern",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 19,
    category: "TF",
    locale: "en",
    question_text: "What kind of lover do you sometimes fantasize about?",
    option_a_label: "Someone who gently accepts me",
    option_b_label: "Someone I want to protect",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
  {
    question_number: 20,
    category: "SN",
    locale: "en",
    question_text: "Which type do you think you are?",
    option_a_label: "Someone who seriously considers the future",
    option_b_label: "Someone for whom liking them now is enough",
    option_a_value: "S",
    option_b_value: "N",
    weight: 1,
  },
  {
    question_number: 21,
    category: "JP",
    locale: "en",
    question_text: "After starting a relationship, how does your life change?",
    option_a_label: "Time with friends or hobbies remains about the same as before",
    option_b_label: "My partner becomes my top priority",
    option_a_value: "P",
    option_b_value: "J",
    weight: 1,
  },
  {
    question_number: 22,
    category: "EI",
    locale: "en",
    question_text: "When someone loves you, do you feel happy because you're 'needed'?",
    option_a_label: "Yes",
    option_b_label: "No",
    option_a_value: "E",
    option_b_value: "I",
    weight: 1,
  },
  {
    question_number: 23,
    category: "SN",
    locale: "en",
    question_text: "Which type do you think you're closer to?",
    option_a_label: "I value the feeling of liking over ideals or conditions",
    option_b_label: "I clearly think about and seriously look for someone who meets my ideals",
    option_a_value: "N",
    option_b_value: "S",
    weight: 1,
  },
  {
    question_number: 24,
    category: "JP",
    locale: "en",
    question_text: "What's your love style?",
    option_a_label: "Sincere and focused, treating my partner seriously",
    option_b_label: "Free-spirited, loving at my own pace",
    option_a_value: "J",
    option_b_value: "P",
    weight: 1,
  },
  {
    question_number: 25,
    category: "TF",
    locale: "en",
    question_text: "If your partner says 'I'd rather go somewhere else' before a date?",
    option_a_label: "I don't mind as long as they're happy",
    option_b_label: "Let's talk about it first",
    option_a_value: "F",
    option_b_value: "T",
    weight: 1,
  },
];

const ptQuestions = [
  { question_number: 1, category: "TF", locale: "pt", question_text: "Eu prefiro pessoas mais maduras do que eu", option_a_label: "Sim", option_b_label: "Não", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 2, category: "EI", locale: "pt", question_text: "Eu me deixo atrair facilmente pelas pessoas e me apaixono com facilidade", option_a_label: "Sim", option_b_label: "Não", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 3, category: "EI", locale: "pt", question_text: "Quando tenho parceiro(a), evito lugares com muitas pessoas do sexo oposto", option_a_label: "Sim", option_b_label: "Não", option_a_value: "I", option_b_value: "E", weight: 1 },
  { question_number: 4, category: "TF", locale: "pt", question_text: "De modo geral, tendo a ceder ao(à) meu(minha) parceiro(a)", option_a_label: "Sim", option_b_label: "Não", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 5, category: "JP", locale: "pt", question_text: "Tenho tendência a amores não correspondidos", option_a_label: "Sim", option_b_label: "Não", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 6, category: "JP", locale: "pt", question_text: "Quando estou com meu(minha) parceiro(a), qual sentimento é mais forte?", option_a_label: "Ir para onde eu quero", option_b_label: "Ir para onde meu(minha) parceiro(a) quer", option_a_value: "J", option_b_value: "P", weight: 1 },
  { question_number: 7, category: "SN", locale: "pt", question_text: "Se tivesse que escolher, você tende a:", option_a_label: "Apaixonar-se gradualmente por alguém", option_b_label: "Apaixonar-se de repente por alguém", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 8, category: "JP", locale: "pt", question_text: "Nos relacionamentos, sou frequentemente passivo(a) e facilmente conduzido(a) pelo(a) parceiro(a)", option_a_label: "Sim", option_b_label: "Não", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 9, category: "EI", locale: "pt", question_text: "Seu(sua) parceiro(a) já disse que você é grudento(a), ou você acha que é?", option_a_label: "Sim", option_b_label: "Não", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 10, category: "TF", locale: "pt", question_text: "Às vezes acho meu(minha) parceiro(a) infantil e fofo(a)", option_a_label: "Sim", option_b_label: "Não", option_a_value: "T", option_b_value: "F", weight: 1 },
  { question_number: 11, category: "JP", locale: "pt", question_text: "No amor, qual lado de você é mais forte?", option_a_label: "Espírito livre", option_b_label: "Sério(a) e comprometido(a)", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 12, category: "TF", locale: "pt", question_text: "Se seu(sua) parceiro(a) sugerir uma caminhada ao voltar do encontro, o que você faria?", option_a_label: "Talvez eu recuse se estiver cansado(a)", option_b_label: "Eu iria mesmo um pouco cansado(a)", option_a_value: "T", option_b_value: "F", weight: 1 },
  { question_number: 13, category: "SN", locale: "pt", question_text: "Ao procurar um(a) parceiro(a), qual é seu estado de espírito?", option_a_label: "Tenho imagem clara do tipo ideal e quase não muda", option_b_label: "Meu tipo ideal é quem eu me apaixono", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 14, category: "EI", locale: "pt", question_text: "Você acha que gosta de assumir a liderança no relacionamento?", option_a_label: "Sim", option_b_label: "Não", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 15, category: "JP", locale: "pt", question_text: "Sobre uma relação 'mais que amigos, menos que namorados'", option_a_label: "Consigo aproveitar mantendo assim", option_b_label: "Quero começar a namorar logo", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 16, category: "SN", locale: "pt", question_text: "Você consegue explicar claramente e logicamente por que gostou de alguém?", option_a_label: "Sim", option_b_label: "Não", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 17, category: "TF", locale: "pt", question_text: "Se seu(sua) parceiro(a) quiser que você o(a) acompanhe a uma loja que não te interessa, o que faria?", option_a_label: "Eu iria para fazê-lo(a) feliz", option_b_label: "Sinceramente, eu não gostaria de ir", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 18, category: "JP", locale: "pt", question_text: "Após começar a namorar, quanta atenção/envolvimento você deseja do(a) parceiro(a)?", option_a_label: "Prefiro menos interferência e mais liberdade", option_b_label: "Fico feliz se ele(a) cuidar de mim e demonstrar atenção", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 19, category: "TF", locale: "pt", question_text: "Que tipo de amante você às vezes imagina?", option_a_label: "Alguém que me acolhe gentilmente", option_b_label: "Alguém que eu queira proteger", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 20, category: "SN", locale: "pt", question_text: "Qual tipo você acha que é?", option_a_label: "Quem pensa seriamente no futuro", option_b_label: "Para quem 'gostar agora' já basta", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 21, category: "JP", locale: "pt", question_text: "Após bercinta, como sua vida muda?", option_a_label: "Tempo com amigos/hobbies quase igual a antes", option_b_label: "Meu(minha) parceiro(a) vira prioridade máxima", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 22, category: "EI", locale: "pt", question_text: "Quando alguém te ama, você fica feliz por ser 'necessário(a)'?", option_a_label: "Sim", option_b_label: "Não", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 23, category: "SN", locale: "pt", question_text: "Você está mais próximo(a) de qual tipo?", option_a_label: "Valorizo mais o sentir do que ideais/condições", option_b_label: "Penso claramente e procuro quem atenda meu ideal", option_a_value: "N", option_b_value: "S", weight: 1 },
  { question_number: 24, category: "JP", locale: "pt", question_text: "Qual é seu estilo de amar?", option_a_label: "Sincero(a) e focado(a), tratando o parceiro com seriedade", option_b_label: "Livre, amo no meu ritmo", option_a_value: "J", option_b_value: "P", weight: 1 },
  { question_number: 25, category: "TF", locale: "pt", question_text: "Se antes do encontro seu(sua) parceiro(a) disser 'melhor irmos a outro lugar'?", option_a_label: "Não me importo se ele(a) ficar feliz", option_b_label: "Vamos conversar primeiro", option_a_value: "F", option_b_value: "T", weight: 1 },
];

const msQuestions = [
  { question_number: 1, category: "TF", locale: "ms", question_text: "Saya lebih suka orang yang lebih matang daripada saya", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 2, category: "EI", locale: "ms", question_text: "Saya mudah tertarik pada orang dan mudah jatuh cinta", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 3, category: "EI", locale: "ms", question_text: "Apabila saya mempunyai pasangan, saya cuba mengelakkan tempat yang ramai orang berlainan jantina", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "I", option_b_value: "E", weight: 1 },
  { question_number: 4, category: "TF", locale: "ms", question_text: "Saya cenderung menyesuaikan diri dengan pasangan", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 5, category: "JP", locale: "ms", question_text: "Saya cenderung kepada cinta bertepuk sebelah tangan", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 6, category: "JP", locale: "ms", question_text: "Apabila bersama pasangan, perasaan mana biasanya lebih kuat?", option_a_label: "Pergi ke tempat yang saya mahu", option_b_label: "Pergi ke tempat yang pasangan saya mahu", option_a_value: "J", option_b_value: "P", weight: 1 },
  { question_number: 7, category: "SN", locale: "ms", question_text: "Jika perlu memilih, anda cenderung kepada:", option_a_label: "Jatuh cinta secara beransur-ansur", option_b_label: "Jatuh cinta secara tiba-tiba", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 8, category: "JP", locale: "ms", question_text: "Dalam hubungan, saya sering pasif dan mudah dipimpin oleh pasangan", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 9, category: "EI", locale: "ms", question_text: "Pernahkah pasangan berkata anda terlalu bergantung, atau anda rasa begitu?", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 10, category: "TF", locale: "ms", question_text: "Kadang-kadang saya rasa pasangan saya kebudak-budakan dan comel", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "T", option_b_value: "F", weight: 1 },
  { question_number: 11, category: "JP", locale: "ms", question_text: "Dalam cinta, sisi mana diri anda lebih kuat?", option_a_label: "Bebas dan spontan", option_b_label: "Serius dan komited", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 12, category: "TF", locale: "ms", question_text: "Jika pasangan mencadangkan berjalan-jalan dalam perjalanan pulang dari janji temu?", option_a_label: "Jika penat, mungkin saya menolak", option_b_label: "Saya tetap pergi walaupun sedikit penat", option_a_value: "T", option_b_value: "F", weight: 1 },
  { question_number: 13, category: "SN", locale: "ms", question_text: "Apabila mencari pasangan, fikiran anda biasanya bagaimana?", option_a_label: "Gambaran jenis ideal saya jelas dan jarang berubah", option_b_label: "Jenis ideal saya ialah orang yang saya jatuh cinta", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 14, category: "EI", locale: "ms", question_text: "Adakah anda jenis yang suka memimpin dalam hubungan?", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 15, category: "JP", locale: "ms", question_text: "Mengenai hubungan 'lebih daripada kawan, kurang daripada kekasih'", option_a_label: "Saya boleh menikmatinya seperti sedia ada", option_b_label: "Saya mahu cepat memulakan hubungan", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 16, category: "SN", locale: "ms", question_text: "Bolehkah anda terangkan dengan jelas dan logik mengapa anda menyukai seseorang?", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 17, category: "TF", locale: "ms", question_text: "Jika pasangan mahu anda temankan ke kedai yang anda tidak minati?", option_a_label: "Saya akan pergi untuk menggembirakannya", option_b_label: "Sejujurnya, saya tidak begitu mahu pergi", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 18, category: "JP", locale: "ms", question_text: "Selepas mula bercinta, berapa banyak perhatian atau campur tangan yang anda mahukan daripada pasangan?", option_a_label: "Saya lebih suka kurang campur tangan dan lebih kebebasan", option_b_label: "Saya gembira jika dia ambil berat dan menunjukkan perhatian", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 19, category: "TF", locale: "ms", question_text: "Apakah jenis kekasih yang kadang-kadang anda bayangkan?", option_a_label: "Seseorang yang menerima saya dengan lembut", option_b_label: "Seseorang yang saya ingin lindungi", option_a_value: "F", option_b_value: "T", weight: 1 },
  { question_number: 20, category: "SN", locale: "ms", question_text: "Anda rasa diri anda jenis yang mana?", option_a_label: "Seseorang yang memikirkan masa depan dengan serius", option_b_label: "Seseorang yang cukup dengan perasaan suka pada saat ini", option_a_value: "S", option_b_value: "N", weight: 1 },
  { question_number: 21, category: "JP", locale: "ms", question_text: "Selepas bercinta, bagaimana kehidupan anda berubah?", option_a_label: "Masa untuk kawan/hobi hampir sama seperti sebelum ini", option_b_label: "Pasangan menjadi keutamaan utama saya", option_a_value: "P", option_b_value: "J", weight: 1 },
  { question_number: 22, category: "EI", locale: "ms", question_text: "Apabila seseorang menyayangi anda, adakah anda berasa bahagia kerana anda 'diperlukan'?", option_a_label: "Ya", option_b_label: "Tidak", option_a_value: "E", option_b_value: "I", weight: 1 },
  { question_number: 23, category: "SN", locale: "ms", question_text: "Anda rasa anda lebih dekat dengan jenis yang mana?", option_a_label: "Saya lebih mementingkan perasaan suka berbanding ideal atau syarat", option_b_label: "Saya jelas berfikir dan mencari seseorang yang memenuhi ideal saya", option_a_value: "N", option_b_value: "S", weight: 1 },
  { question_number: 24, category: "JP", locale: "ms", question_text: "Gaya cinta anda?", option_a_label: "Ikhlas dan fokus, melayan pasangan dengan serius", option_b_label: "Bebas, mengasihi mengikut rentak sendiri", option_a_value: "J", option_b_value: "P", weight: 1 },
  { question_number: 25, category: "TF", locale: "ms", question_text: "Jika pasangan berkata 'lebih baik pergi tempat lain' sebelum janji temu?", option_a_label: "Saya tidak kisah asalkan dia gembira", option_b_label: "Mari bincang dahulu", option_a_value: "F", option_b_value: "T", weight: 1 },
];

async function seed() {
  console.log("开始初始化测试题目...");
  
  try {
    // 插入/更新题目（zh/ja/en/pt/ms）...
    console.log("\n插入/更新题目（zh/ja/en/pt/ms）...");
    for (const list of [zhQuestions, jaQuestions, enQuestions, ptQuestions, msQuestions]) {
      for (const q of list) {
        await db()
          .insert(quizQuestions)
          .values(q)
          .onConflictDoUpdate({
            target: [quizQuestions.question_number, quizQuestions.locale],
            set: {
              category: q.category,
              question_text: q.question_text,
              option_a_label: q.option_a_label,
              option_b_label: q.option_b_label,
              option_a_value: q.option_a_value,
              option_b_value: q.option_b_value,
              weight: q.weight,
              updated_at: new Date(),
            },
          });
        console.log(`✓ 题目 ${q.question_number} (${q.locale}) - ${q.category}`);
      }
    }
    
    console.log("\n✅ 题目初始化完成！");
    console.log(`总共插入了 ${zhQuestions.length + jaQuestions.length + enQuestions.length + ptQuestions.length + msQuestions.length} 道题目`);
    console.log("\n📊 题目分布:");
    console.log(`  - 中文: ${zhQuestions.length} 题`);
    console.log(`  - 日语: ${jaQuestions.length} 题`);
    console.log(`  - 英语: ${enQuestions.length} 题`);
    console.log(`  - 葡萄牙语: ${ptQuestions.length} 题`);
    console.log(`  - 马来语: ${msQuestions.length} 题`);
    
    // 统计各维度题目数量
    const categories = { EI: 0, SN: 0, TF: 0, JP: 0 };
    zhQuestions.forEach(q => categories[q.category as keyof typeof categories]++);
    console.log("\n�� 各维度题目数量（每种语言）:");
    console.log(`  - EI (外向/内向): ${categories.EI} 题`);
    console.log(`  - SN (感觉/直觉): ${categories.SN} 题`);
    console.log(`  - TF (思考/情感): ${categories.TF} 题`);
    console.log(`  - JP (判断/知觉): ${categories.JP} 题`);
  } catch (error) {
    console.error("❌ 初始化失败:", error);
    throw error;
  }
}

// 执行
seed()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });